// Generated by ./build-aux/bin/authors.h-gen, do not edit by hand.

#define PACKAGE_SHORT_AUTHORS \


#define PACKAGE_AUTHORS \
  "alexandre.girold\n"                                                       \
  "wadhah.ouled-ameur\n"                                                     \
  "vincent.stauber\n"
